// Renders a "behavior contract" — a human-readable markdown summary of what
// the AST analyzer found in a component. P11 shipping criterion: the file
// lives alongside the generated spec so the developer can read it before
// approving the test suite reactlens wrote.
//
// Pure function. The companion writer in commands/generate.ts handles I/O.
import type { ComponentAnalysis, VisualState } from '../ast/component-analyzer';

export type ContractOptions = {
  // ISO date or any short string to stamp on the document. Threaded as an
  // option so the unit tests can pin a value; production passes the current
  // local date.
  generatedAt: string;
  // v0.3 slice 6: when 'component-object', append the CO surface section
  // documenting how specs address the component and which hooks are
  // assertable. Omitted ⇒ no CO section (POM-default behavior preserved).
  pattern?: 'pom' | 'component-object';
};

function renderState(state: VisualState): string {
  const lines: string[] = [`### \`${state.name}\``, '', state.description, ''];
  if (state.conditions.length > 0) {
    lines.push(`**Conditions**: ${state.conditions.map((c) => `\`${c}\``).join(', ')}`, '');
  }
  if (state.apiCalls.length > 0) {
    lines.push(`**API calls**: ${state.apiCalls.map((c) => `\`${c}\``).join(', ')}`, '');
  }
  return lines.join('\n');
}

function renderHooks(hooks: ComponentAnalysis['hooks']): string {
  if (hooks.length === 0) return '_no hooks captured_';
  return hooks
    .map((h) => {
      const initial = h.initial !== undefined ? ` — initial: \`${h.initial}\`` : '';
      return `- \`${h.name}\`${initial}`;
    })
    .join('\n');
}

function renderEndpoints(endpoints: string[]): string {
  if (endpoints.length === 0) return '_no endpoints captured_';
  return endpoints.map((e) => `- \`${e}\``).join('\n');
}

function renderComponentObjectSurface(analysis: ComponentAnalysis): string {
  const lines: string[] = [
    '## Component-Object surface',
    '',
    `Specs in this project use the Component-Object Pattern (\`pattern: 'component-object'\` in \`reactlens.config.ts\`). They assert directly on \`${analysis.componentName}\`'s props via the runtime helper:`,
    '',
    '```ts',
    `await expect.poll(() => Component('${analysis.componentName}').props.<key>, { timeout: 5_000 }).toBe(<expected>);`,
    '```',
    '',
    `Addressing key: \`Component('${analysis.componentName}')\` (matches the React fiber \`displayName\`).`,
    '',
    '### Assertable surface (hooks captured by AST)',
    '',
  ];
  if (analysis.hooks.length === 0) {
    lines.push(
      '_no hooks captured — the AST analyzer did not find `useState`/`useReducer`/`useQuery`/`useSWR`/`useForm` calls in this component. CO specs can still assert on whatever props the React fiber emits at runtime, but the AST has nothing to enumerate here._',
    );
  } else {
    lines.push(
      'These hook calls were enumerated from the source. The actual props that reach `Component(...).props.<x>` come from the React fiber at runtime — open the reactlens dashboard during a run to see the live shape. Listed here as authoring hints, not as a closed enumeration:',
      '',
    );
    for (const h of analysis.hooks) {
      const initial = h.initial !== undefined ? ` — initial: \`${h.initial}\`` : '';
      lines.push(`- \`${h.name}\`${initial}`);
    }
  }
  lines.push('');
  return lines.join('\n');
}

export function renderContract(analysis: ComponentAnalysis, opts: ContractOptions): string {
  const stateCount = analysis.states.length;
  const stateCountText = stateCount === 1 ? '**1 visual state**' : `**${stateCount} distinct visual states**`;
  const sections: string[] = [
    `# ${analysis.componentName} — behavior contract`,
    '',
    `**Source**: \`${analysis.filePath}\`  `,
    `**Generated by**: \`reactlens generate\` · ${opts.generatedAt}`,
    '',
    '## Visual states',
    '',
    `reactlens analyzed \`${analysis.componentName}\` and found ${stateCountText}. Each state is a render branch the component can be in, derived from \`useState\`/\`useReducer\`/query-hook flags and conditional JSX. The generated spec exercises every state listed below — if one is wrong or missing, edit the component source and re-run \`reactlens generate\`.`,
    '',
    analysis.states.map(renderState).join('\n'),
    '## Hooks',
    '',
    renderHooks(analysis.hooks),
    '',
    '## API endpoints',
    '',
    renderEndpoints(analysis.endpoints),
    '',
  ];
  if (opts.pattern === 'component-object') {
    sections.push(renderComponentObjectSurface(analysis));
  }
  sections.push(
    '---',
    '',
    `> This file is **overwritten on every \`reactlens generate\` run**. Don't hand-edit it — change the component source instead.`,
    '',
  );
  return sections.join('\n');
}
