// Renders a "behavior contract" — a human-readable markdown summary of what
// the AST analyzer found in a component. P11 shipping criterion: the file
// lives alongside the generated spec so the developer can read it before
// approving the test suite reactlens wrote.
//
// Pure function. The companion writer in commands/generate.ts handles I/O.
import type { ComponentAnalysis, VisualState } from '../ast/component-analyzer';

export type ContractOptions = {
  // ISO date or any short string to stamp on the document. Threaded as an
  // option so the unit tests can pin a value; production passes the current
  // local date.
  generatedAt: string;
};

function renderState(state: VisualState): string {
  const lines: string[] = [`### \`${state.name}\``, '', state.description, ''];
  if (state.conditions.length > 0) {
    lines.push(`**Conditions**: ${state.conditions.map((c) => `\`${c}\``).join(', ')}`, '');
  }
  if (state.apiCalls.length > 0) {
    lines.push(`**API calls**: ${state.apiCalls.map((c) => `\`${c}\``).join(', ')}`, '');
  }
  return lines.join('\n');
}

function renderHooks(hooks: ComponentAnalysis['hooks']): string {
  if (hooks.length === 0) return '_no hooks captured_';
  return hooks
    .map((h) => {
      const initial = h.initial !== undefined ? ` — initial: \`${h.initial}\`` : '';
      return `- \`${h.name}\`${initial}`;
    })
    .join('\n');
}

function renderEndpoints(endpoints: string[]): string {
  if (endpoints.length === 0) return '_no endpoints captured_';
  return endpoints.map((e) => `- \`${e}\``).join('\n');
}

export function renderContract(analysis: ComponentAnalysis, opts: ContractOptions): string {
  const stateCount = analysis.states.length;
  const stateCountText = stateCount === 1 ? '**1 visual state**' : `**${stateCount} distinct visual states**`;
  return [
    `# ${analysis.componentName} — behavior contract`,
    '',
    `**Source**: \`${analysis.filePath}\`  `,
    `**Generated by**: \`reactlens generate\` · ${opts.generatedAt}`,
    '',
    '## Visual states',
    '',
    `reactlens analyzed \`${analysis.componentName}\` and found ${stateCountText}. Each state is a render branch the component can be in, derived from \`useState\`/\`useReducer\`/query-hook flags and conditional JSX. The generated spec exercises every state listed below — if one is wrong or missing, edit the component source and re-run \`reactlens generate\`.`,
    '',
    analysis.states.map(renderState).join('\n'),
    '## Hooks',
    '',
    renderHooks(analysis.hooks),
    '',
    '## API endpoints',
    '',
    renderEndpoints(analysis.endpoints),
    '',
    '---',
    '',
    `> This file is **overwritten on every \`reactlens generate\` run**. Don't hand-edit it — change the component source instead.`,
    '',
  ].join('\n');
}
