import { describe, expect, it } from 'vitest';
import { renderContract } from '../../src/generator/contract';
import type { ComponentAnalysis } from '../../src/ast/component-analyzer';

const FIXED_DATE = '2026-05-14';

function analysis(overrides: Partial<ComponentAnalysis> = {}): ComponentAnalysis {
  return {
    componentName: 'CheckoutPage',
    filePath: 'src/pages/CheckoutPage.tsx',
    states: [
      { name: 'loading', description: 'returns while the checkout state is fetching', conditions: ['query.isPending'], apiCalls: ['/api/checkout/state'] },
      { name: 'success', description: 'default success render', conditions: ['query.isSuccess'], apiCalls: ['/api/checkout/state'] },
    ],
    hooks: [
      { name: 'useState', initial: "'idle'" },
      { name: 'useQuery' },
    ],
    endpoints: ['/api/checkout/state', '/api/checkout/submit'],
    ...overrides,
  };
}

describe('renderContract', () => {
  it('produces a single markdown document with H1, source path, and visual states section', () => {
    const md = renderContract(analysis(), { generatedAt: FIXED_DATE });
    expect(md).toMatch(/^# CheckoutPage — behavior contract\n/);
    expect(md).toContain('**Source**: `src/pages/CheckoutPage.tsx`');
    expect(md).toContain(`Generated by**: \`reactlens generate\` · ${FIXED_DATE}`);
    expect(md).toContain('## Visual states');
  });

  it('renders one h3 per visual state with conditions and api calls', () => {
    const md = renderContract(analysis(), { generatedAt: FIXED_DATE });
    expect(md).toContain('### `loading`');
    expect(md).toContain('returns while the checkout state is fetching');
    expect(md).toContain('**Conditions**: `query.isPending`');
    expect(md).toContain('**API calls**: `/api/checkout/state`');
    expect(md).toContain('### `success`');
  });

  it('lists hooks and endpoints in their own sections', () => {
    const md = renderContract(analysis(), { generatedAt: FIXED_DATE });
    expect(md).toContain('## Hooks');
    expect(md).toContain('`useState`');
    expect(md).toContain("initial: `'idle'`");
    expect(md).toContain('## API endpoints');
    expect(md).toContain('`/api/checkout/state`');
    expect(md).toContain('`/api/checkout/submit`');
  });

  it('warns the reader that the file is regenerated each run (not hand-edited)', () => {
    const md = renderContract(analysis(), { generatedAt: FIXED_DATE });
    expect(md).toMatch(/overwritten on every `reactlens generate` run/i);
  });

  it('handles a state with no conditions / no api calls without emitting empty bullets', () => {
    const a = analysis({
      states: [{ name: 'idle', description: 'static initial render', conditions: [], apiCalls: [] }],
      hooks: [],
      endpoints: [],
    });
    const md = renderContract(a, { generatedAt: FIXED_DATE });
    expect(md).toContain('### `idle`');
    expect(md).not.toContain('**Conditions**:');
    expect(md).not.toContain('**API calls**:');
    expect(md).toContain('_no hooks captured_');
    expect(md).toContain('_no endpoints captured_');
  });

  it('produces stable output given identical input (deterministic)', () => {
    const a = analysis();
    expect(renderContract(a, { generatedAt: FIXED_DATE })).toBe(renderContract(a, { generatedAt: FIXED_DATE }));
  });

  describe('Component-Object Pattern surface (v0.3 slice 6)', () => {
    it('omits the CO section by default (pattern not specified)', () => {
      const md = renderContract(analysis(), { generatedAt: FIXED_DATE });
      expect(md).not.toContain('## Component-Object surface');
    });

    it('omits the CO section when pattern is pom', () => {
      const md = renderContract(analysis(), { generatedAt: FIXED_DATE, pattern: 'pom' });
      expect(md).not.toContain('## Component-Object surface');
    });

    it('includes a CO surface section when pattern is component-object', () => {
      const md = renderContract(analysis(), {
        generatedAt: FIXED_DATE,
        pattern: 'component-object',
      });
      expect(md).toContain('## Component-Object surface');
      // Addressing key is the component display name.
      expect(md).toContain("`Component('CheckoutPage')`");
      // Mentions expect.poll composition (locked in the design doc).
      expect(md).toMatch(/expect\.poll/);
    });

    it('lists assertable hooks under the CO section', () => {
      const md = renderContract(analysis(), {
        generatedAt: FIXED_DATE,
        pattern: 'component-object',
      });
      // Hooks already enumerated by the AST become candidate assertion
      // targets; the section advertises them.
      expect(md).toContain('### Assertable surface (hooks captured by AST)');
      expect(md).toContain('`useState`');
      expect(md).toContain('`useQuery`');
    });

    it('hedges honestly when no hooks were captured', () => {
      const a = analysis({ hooks: [] });
      const md = renderContract(a, { generatedAt: FIXED_DATE, pattern: 'component-object' });
      expect(md).toContain('## Component-Object surface');
      expect(md).toMatch(/no hooks captured/i);
    });
  });
});
